### ISSUE TITLE
大佬，qs版的排序是按什么来的？

### ISSUE THREAD

**Issue by jqhr** [Ace-Who/rime-xuma-spelling#13]
举个例子，
“皮”这个字，我输入"dp"，

https://user-images.githubusercontent.com/23305067/189464627-62ff977e-9c89-4df0-92d2-a031ace6ccb1.mp4

第一个为何不是“皮”也不是词呢？

**Comment by Ace-Who** [comment]
简码主要依据字频设置。「张」的字频显著高于「皮」，所以把 dp 首选让给「张」。

同时，把「张」的前三码 dpc，换给被挤出首选位的字根「皮」，称为「皮」的字根扩展码。详见说明 https://github.com/Ace-Who/rime-xuma#readme 「二简置换码」一节。

**Comment by jqhr** [comment]
这个我明白了。
不过，有些生僻字比其他的词组靠前是怎么回事呢？
比如“其他”，直接输入"hqtb"，

https://user-images.githubusercontent.com/23305067/189508374-727cd26c-733d-4542-929e-b7ed20b0d9a5.mp4

就像这个一样。

**Comment by Ace-Who** [comment]
码表顺序如此，单字优先。可以通过修改码表实现想要的排序。

**Comment by jqhr** [comment]
ok,用by_weight

**Comment by Ace-Who** [comment]
本方案词典中提供的权重，不保证效果，也没有覆盖所有词条，注释里有解释。

**Comment by jqhr** [comment]
ok

**Comment by jqhr** [comment]
@Ace-Who 
大佬，使用`by_weight`还是有的生僻字排名靠前，比如`cemb`这个，候选字就两个，一个是`贯`，另一个是`𰌇`，可是`贯`的权重比`𰌇`高，是不是因为没有权重值权重就无限⼤？

**Comment by Ace-Who** [comment]
默认开启「全码后置」，即有简码的字，全码后置。「贯」有简码 `cem`，所以全码 `cemb` 后置。

**Comment by jqhr** [comment]
后置后的`cem`也有别的字，某些时候就很头疼。
