### ISSUE TITLE
关于徐码作者

### ISSUE THREAD

**Issue by WIZARDELF** [Ace-Who/rime-xuma-spelling#14]
开篇README里讲：“原始码表由徐码作者徐国银先生提供，……”。我看过一些报道，说作者叫“徐复来”：
- https://www.nbei.net/2021/1014/c174a10959/page.htm
- https://new.qq.com/omn/20211105/20211105A079SB00.html
- http://news.cnnb.com.cn/system/2014/06/04/008077940.shtml

不知道是否应该更新一下。

另外，能不能放开版权啊，老人家哪天百年了，这么好的东西算谁的？我也没细看码表，听说只有二进制，作者西去之后，咋个维护啊。

**Comment by Ace-Who** [comment]
本项目利用 Rime 程序实现由徐国银发明的徐码输入法。所有代码都已公开。
本项目与徐复来发明的徐码无关。
